builders:
  contract_generator:
    import: "package:starknet_builder/src/builder.dart"
    builder_factories: ["contractGenerator", "legacyContractGenerator"]
    build_extensions: {".abi.json": [".g.dart"], ".sierra.json": [".sierra.g.dart"]}
    auto_apply: root_package
    build_to: source

