name: starknet
description: Dart SDK for StarkNet
version: 0.0.1
repository: https://github.com/gabsn/starknet.dart

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  crypto: ^3.0.2
  ecdsa: ^0.0.4
  elliptic: ^0.3.8
  freezed_annotation: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.5.0
  pointycastle: ^3.6.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  lints: ^2.0.0
  test: ^1.16.0
