name: starknet_example
description: The Dart SDK builder for contracts on starknet
version: 0.0.1
repository: https://github.com/gabsn/starknet.dart

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  starknet:
  starknet_builder:

dev_dependencies:
  build_runner: ^2.1.11
