[project]
protostar-version = "0.8.1"
lib-path = "lib"
cairo-path = ["./lib/cairo_contracts/src"]

[contracts]
proxy = ["lib/cairo_contracts/src/openzeppelin/upgrades/presets/Proxy.cairo"]
erc20 = [
    "lib/cairo_contracts/src/openzeppelin/token/erc20/presets/ERC20Upgradeable.cairo"
]
erc721 = [
    "lib/cairo_contracts/src/openzeppelin/token/erc721/presets/ERC721MintableBurnable.cairo"
]
